Minimize image

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,26 +1,22 @@
 # Continuous integration testing for ChRIS Plugin.
-# https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds
+# https://github.com/FNNDSC/python-chrisapp-template/wiki/Continuous-Integration
 #
-# - automatically run pytest
-# - on push to main, build and push container images as ":latest"
-# - on tag, build and push container images with tag
-# - on release, upload plugin description to https://chrisstore.co
+# - on push to master: build and push container images as ":latest"
+# - on push to semver tag: build and push container image with tag and
+#                          upload plugin description to https://chrisstore.co
 
 name: build
 
 on:
   push:
     branches: [ master ]
-  pull_request:
-    branches: [ master ]
-  release:
-    types: [ created ]
+    tags:
+      - "v?[0-9]+.[0-9]+.[0-9]+*"
 
 jobs:
   build:
     name: Build
-    if: github.event_name == 'push' || github.event_name == 'release'
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
 
     # A local registry helps us reuse the built image between steps
     services:
@@ -33,7 +29,7 @@ jobs:
       - name: Get git tag
         id: git_info
         if: startsWith(github.ref, 'refs/tags/')
-        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
+        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
       - name: Get project info
         id: determine
         env:
@@ -50,8 +46,8 @@ jobs:
 
           dock_image=$repo:$tag
           echo $dock_image
-          echo "::set-output name=dock_image::$dock_image"
-          echo "::set-output name=repo::$repo"
+          echo "dock_image=$dock_image" >> $GITHUB_OUTPUT
+          echo "repo=$repo" >> $GITHUB_OUTPUT
 
       - uses: actions/checkout@v3
         # QEMU is used for non-x86_64 builds
@@ -62,7 +58,7 @@ jobs:
           driver-opts: network=host
         # cache slightly improves rebuild time
       - name: Cache Docker layers
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: /tmp/.buildx-cache
           key: ${{ runner.os }}-buildx-${{ github.sha }}
@@ -98,6 +94,26 @@ jobs:
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
 
+      - name: Run examples
+        run: |
+          dock_image=${{ steps.determine.outputs.dock_image }}
+          output_dir=$(mktemp -d)
+          docker run --rm -u "$(id -u):$(id -g)" \
+            -v "$PWD/examples/incoming:/incoming:ro" \
+            -v "$output_dir:/outgoing:rw" \
+            localhost:5000/$dock_image smtherr /incoming /outgoing
+          
+          for expected_file in $(find examples/outgoing -type f); do
+            fname="${expected_file##*/}"
+            out_path="$output_dir/$fname"
+            printf "Checking output %s exists..." "$out_path"
+            if [ -f "$out_path" ]; then
+              echo "ok"
+            else
+              echo "not found"
+              exit 1
+            fi
+          done
       - name: Get plugin meta
         id: pluginmeta
         run: |
@@ -105,10 +121,10 @@ jobs:
           dock_image=${{ steps.determine.outputs.dock_image }}
           docker run --rm localhost:5000/$dock_image chris_plugin_info > /tmp/description.json
           jq < /tmp/description.json  # pretty print in log
-          echo "::set-output name=title::$(jq -r '.title' < /tmp/description.json)"
+          echo "title=$(jq -r '.title' < /tmp/description.json)" >> $GITHUB_OUTPUT
 
       - name: Update DockerHub description
-        uses: peter-evans/dockerhub-description@v2
+        uses: peter-evans/dockerhub-description@v3
         continue-on-error: true  # it is not crucial that this works
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
@@ -118,7 +134,7 @@ jobs:
           repository: ${{ steps.determine.outputs.repo }}
 
       - name: Upload to ChRIS Store
-        if: github.event_name == 'release'
+        if: steps.git_info.outcome != 'skipped'
         uses: FNNDSC/chrisstore-action@master
         with:
           descriptor_file: /tmp/description.json
